//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWeb.srDescuentos {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srDescuentos.wsDescuentosSoap")]
    public interface wsDescuentosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Agregar(string Discounttype, string Stor_id, string Lowqty, string Highqty, string Discount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> AgregarAsync(string Discounttype, string Stor_id, string Lowqty, string Highqty, string Discount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Actualizar(string Discounttype, string Stor_id, string Lowqty, string Highqty, string Discount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> ActualizarAsync(string Discounttype, string Stor_id, string Lowqty, string Highqty, string Discount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Eliminar(string discounttype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> EliminarAsync(string discounttype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buscar(string texto, string criterio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsDescuentosSoapChannel : ClienteWeb.srDescuentos.wsDescuentosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsDescuentosSoapClient : System.ServiceModel.ClientBase<ClienteWeb.srDescuentos.wsDescuentosSoap>, ClienteWeb.srDescuentos.wsDescuentosSoap {
        
        public wsDescuentosSoapClient() {
        }
        
        public wsDescuentosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsDescuentosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsDescuentosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsDescuentosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public string[] Agregar(string Discounttype, string Stor_id, string Lowqty, string Highqty, string Discount) {
            return base.Channel.Agregar(Discounttype, Stor_id, Lowqty, Highqty, Discount);
        }
        
        public System.Threading.Tasks.Task<string[]> AgregarAsync(string Discounttype, string Stor_id, string Lowqty, string Highqty, string Discount) {
            return base.Channel.AgregarAsync(Discounttype, Stor_id, Lowqty, Highqty, Discount);
        }
        
        public string[] Actualizar(string Discounttype, string Stor_id, string Lowqty, string Highqty, string Discount) {
            return base.Channel.Actualizar(Discounttype, Stor_id, Lowqty, Highqty, Discount);
        }
        
        public System.Threading.Tasks.Task<string[]> ActualizarAsync(string Discounttype, string Stor_id, string Lowqty, string Highqty, string Discount) {
            return base.Channel.ActualizarAsync(Discounttype, Stor_id, Lowqty, Highqty, Discount);
        }
        
        public string[] Eliminar(string discounttype) {
            return base.Channel.Eliminar(discounttype);
        }
        
        public System.Threading.Tasks.Task<string[]> EliminarAsync(string discounttype) {
            return base.Channel.EliminarAsync(discounttype);
        }
        
        public System.Data.DataSet Buscar(string texto, string criterio) {
            return base.Channel.Buscar(texto, criterio);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio) {
            return base.Channel.BuscarAsync(texto, criterio);
        }
    }
}
